[tool.poetry]
name = "monarch-ingest"
version = "0.1.0"
description = ""
authors = ["Kevin Schaper <kevinschaper@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7, <=3.9"
autoflake = "^1.4"
flake8 = "^3.9.2"
isort = "^5.9.1"
importlib-metadata = "^4.6.1"
mkdocs = "^1.2.2"
mkdocs-material = "^7.2.4"
kgx = "^1.5.3"
koza = "0.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
